default-storage-provider: fs
local-storage-prefix: $SCRATCH/arguelles_delgado_lab/Users/$USER/

restart-times: 2
cores: 8
jobs: 100
latency-wait: 120
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
conda-frontend: mamba

executor: slurm
default-resources: 
  - slurm_account="arguelles_delgado_lab"
  - slurm_partition=shared
  - mem_mb=10000
  - runtime=60 # minutes