import numpy as np


configfile: "config/hnl_190301.yaml"
conda: "hnl_icetray.yaml"

ARRAY_NUMS = np.arange(
    0, int(config["n_files"]), 1
)# numpy gives ranges on a half-open interval, so this gives 0-n_files.Last digit is step size
FILE_NUMS = np.arange(0, 1, 1)
print(ARRAY_NUMS)
print(config['n_files'])


rule all:
    input:
        expand(
            "{output_prefix}{set_number}/L2/{array_number}_{file_number}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
            array_number=ARRAY_NUMS,
            file_number=FILE_NUMS,
        ),
    shell:
        ""

rule L2:
    input:
        expand(
            "{output_prefix}{set_number}/L1/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    output:
        expand(
            "{output_prefix}{set_number}/L2/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
        expand(
            "{output_prefix}{set_number}/L2/{{array_number}}_{{file_number}}.hdf5",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    shell:
        "set +u; source /n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/setup.sh; PYTHONPATH=/n/home00/jbook/.local/lib/python3.7/site-packages:$PYTHONPATH; /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/i3/build/env-shell.sh python /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/HNL_search_v2/submission_scripts/process/process_L2.py --identifier_out={config[set_number]} --gcd {config[gcd]} --input {input} --output {output[0]}"


rule L1:
    input:
        expand(
            "{output_prefix}{set_number}/Det/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    output:
        expand(
            "{output_prefix}{set_number}/L1/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
        expand(
            "{output_prefix}{set_number}/L1/{{array_number}}_{{file_number}}.hdf5",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    shell:
        "set +u; pip show numpy; source /n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/setup.sh; PYTHONPATH=/n/home00/jbook/.local/lib/python3.7/site-packages:$PYTHONPATH; pip show numpy; /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/i3/build/env-shell.sh python /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/HNL_search_v2/submission_scripts/process/process_L1.py --identifier_out={config[set_number]} --gcd {config[gcd]} --input {input} --output {output[0]}"


rule detector:
    input:
        expand(
            "{output_prefix}{set_number}/Phot/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    output:
        expand(
            "{output_prefix}{set_number}/Det/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
        expand(
            "{output_prefix}{set_number}/Det/{{array_number}}_{{file_number}}.hdf5",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    params:
        seed=lambda wc: int(wc.array_number) * 1000 + int(wc.file_number),
    # shell:
    #     "set +u; source /n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/setup.sh; PYTHONPATH=/usr/local/lib/python3.7/site-packages:$PYTHONPATH; /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/i3/build/env-shell.sh  python /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/HNL_search_v2/submission_scripts/process/process_Det.py --runnumber {params.seed} --gcdfile {config[gcd]} --infile {input} --outfile {output[0]}"
    shell:
        "set +u; source /n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/setup.sh; PYTHONPATH=/n/home00/jbook/.local/lib/python3.7/site-packages:$PYTHONPATH; /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/i3/build/env-shell.sh python /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/HNL_search_v2/submission_scripts/process/process_Det.py --runnumber {params.seed} --gcdfile {config[gcd]} --infile {input} --outfile {output[0]}"

rule photon:
    input:
        expand(
            "{output_prefix}{set_number}/Gen/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    output:
        expand(
            "{output_prefix}{set_number}/Phot/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
        expand(
            "{output_prefix}{set_number}/Phot/{{array_number}}_{{file_number}}.hdf5",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    params:
        seed=lambda wc: int(wc.array_number) * 1000 + int(wc.file_number),
    resources:
        slurm_partition="arguelles_delgado_gpu",#"gpu_requeue",# 
        slurm_extra="'--gres=gpu:nvidia_a100_1g.10gb:1'",
        runtime=300,
    # singularity:
    #     None,
    # shell:
    #     "sbatch --export=SEED={params.seed},OUTFILE_fullpath={output[0]},INFILE_fullpath={input},GCD={config[gcd]} scripts/photon_jobs.sbatch"
    shell: 
        "set +u; source /n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/setup.sh; /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/i3/build/env-shell.sh python /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/HNL_search_v2/submission_scripts/process/process_Phot.py --runnumber {params.seed} --infile={input} --outfile {output[0]} --gcdfile {config[gcd]} -t"


rule generation:
    output:
        expand(
            "{output_prefix}{set_number}/Gen/{{array_number}}_{{file_number}}.i3.zst",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
        expand(
            "{output_prefix}{set_number}/Gen/{{array_number}}_{{file_number}}.hdf5",
            output_prefix=config["output_prefix"],
            set_number=config["set_number"],
        ),
    params:
        mass=config["hnl_mass"],
        seed=lambda wc: int(wc.array_number) * 1000 + int(wc.file_number),
        n_events={config["n_events"]},
    shell:
        "set +u; source /n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/setup.sh; /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/i3/build/env-shell.sh python /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/HNL_search_v2/submission_scripts/process/process_Gen.py --seed {params.seed} --outfile {output[0]} --nEvents {config[n_events]} -m {config[hnl_mass]}"